[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"
solana_version = "2.1.22"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_advanced = "8WztRFKZTfdSU2J7zGX9JpGDBpBqFqEMjNRQRW9SPRSJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
