[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"
solana_version = "2.1.22"

[features]
resolution = true
skip-lint = false
#seeds = false

[programs.localnet]
anchor_advanced = "8WztRFKZTfdSU2J7zGX9JpGDBpBqFqEMjNRQRW9SPRSJ"
[programs.devnet]
anchor_advanced = "8WztRFKZTfdSU2J7zGX9JpGDBpBqFqEMjNRQRW9SPRSJ"
[programs.mainnet]
anchor_advanced = "8WztRFKZTfdSU2J7zGX9JpGDBpBqFqEMjNRQRW9SPRSJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
#cluster = "Devnet"
#cluster = "Mainnet"

[test]
#startup_wait = 5000
#shutdown_wait = 2000
#upgradeable = false

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
#test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/test1.ts"
#RUST_LOG=
